services:
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql-event-manager
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports: 
      - '3336:3306'
    networks: 
      - event-manager-java
networks:
  event-manager-java:
    driver: bridge